### ISSUE TITLE
Add an editorconfig

### ISSUE THREAD

**Issue by slifty** [OpenTechStrategies/torque-sites#111]
Lets do the [editorconfig](https://editorconfig.org/) thing!

I'll propose:

```
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```

**Comment by frankduncan** [comment]
How does this interact with https://github.com/psf/black ?  We kind of settled on that for now.  I think the `indent_size` for black is 4.

**Comment by slifty** [comment]
Nice -- at the very least I'll set indent size to 4 for python (2 for yml since we seem to use that).

Editorconfig is not a tool, it's just a file that a bunch of editors (or plugins) know how to look for and then use to specify things like default tab sizes etc.

Which is to say: it should interact just fine (or rather, in the same way that having no editorconfig would interact)

That said...

Is black set up in this project yet?  It sounds excellent!  Is there a recommended flow for invoking it pre-commit?

**Comment by frankduncan** [comment]
So, I just run black from the commandline.  And I don't know of any recommended flow for invoking it pre-commit.  I generally forget and then have a "black" commit when I remember.  These are non answers, and some kind of real research shoudl be done!
