### ISSUE TITLE
Add torque param to local

### ISSUE THREAD

**Issue by slifty** [OpenTechStrategies/torque-sites#112]
@hawkinsw noticed that torque isn't running on his local setup and I think this is because there is a new ansible variable used by the torque setup (see the [end of this commit](https://github.com/OpenTechStrategies/torque-sites/commit/13859b26818f660175be9d0d8ab3fc63b9cc4424#)).

To fix this up we'll just need to add a `torquedata_git_version` to the `base/torquedata/ansible/inv/local/gorup_vars/all.tmpl`

(Note that we'll also want to update OpenTechStrategies/torque-devenv to populate that variable via envsubst).

**Comment by frankduncan** [comment]
I'll tackle this.  I think the correct solution is to actually have a default variable that should be overridden for special cases.  I'll update all the files to use this default when appropriate.  That's how it works for the plugin checkout for the competitions.

I should note that the default checkout will be off the postgres branch in torque, which we'll be moving to fully this week!

**Comment by slifty** [comment]
Oh great call -- I'm going to use this pattern for the simplebook version I'm about to add!
