### ISSUE TITLE
Remove 'Printable version' tool from all Torque wikis

### ISSUE THREAD

**Issue by jim-mcgowan** [OpenTechStrategies/torque-sites#131]
Remove the **Printable version** tool from the **Print/export** section of all Torque wikis:

<img width="173" alt="Printable version" src="https://user-images.githubusercontent.com/4147733/119878611-f31a9980-beef-11eb-8aa1-be8ee9f95ca6.png">

**Comment by frankduncan** [comment]
Oh, this is not a part of the book printer!  So this does belong in torque-sites.
