### ISSUE TITLE
Database error when trying to access Active Users page in 100&Change 2017

### ISSUE THREAD

**Issue by jim-mcgowan** [OpenTechStrategies/torque-sites#132]
I get a database error when trying to access the **Active users list** page (https://torque.leverforchange.org/100Change2017/index.php/Special:ActiveUsers) in the 100&Change 2017 Torque wiki:

![Database error](https://user-images.githubusercontent.com/4147733/121056206-989cfb00-c783-11eb-89be-6047ace15047.png)

As part of the effort to clean up user accounts, I need to access this page.

**Comment by frankduncan** [comment]
This was fixed by the mediawiki upgrade!  Yay software upgrades
