### ISSUE TITLE
Edit / Edit Source appears on template sections in the LLIIA competition

### ISSUE THREAD

**Issue by slifty** [OpenTechStrategies/torque-sites#134]
I have not confirmed this on other competitions yet, but LLIIA202's edit interface is... wonky!

In a given proposal, individual sections of the template have the `edit` and `edit source` buttons.  If you click `edit source` you get a message: "Cannot Find Section"

If you click the plain old `edit` then... phewf I just wouldn't do that if I were you!  (I would include a screen shot but it has sensitive information).  It looks like the visual editor edits the wiki page, rather than the template sections; not surprising, but edit should probably not be rendered on that page as a result.

**Comment by frankduncan** [comment]
The template needed the div "torque-wrapper" around it so that the css would hide those buttons.  It's been added!
