### ISSUE TITLE
PickSome is erroring on certain titles

### ISSUE THREAD

**Issue by slifty** [OpenTechStrategies/torque-sites#135]
We were facing an issue where an end user was reporting 500 errors from the server when logging in.

After some investigation I was able to reproduce a 500 error by:

1. activating the PickSome tool (clicking "Start Selecting")
2. Viewing a non-proposal page.

Since the main page after logging in is not a proposal page, this meant that for an end user it would appear that simply logging in would not work.

The error in `apache2/error.log` was:

> [Fri Jul 09 21:28:56.103866 2021] [php7:error] [pid 12439] [client 71.185.65.82:51212] PHP Fatal error: Uncaught TypeError: Argument 1 passed to Title::equals() must implement interface MediaWiki\\Linker\\LinkTarget, null given, called in /home/deploy/RacialEquity2030/mediawiki-1.35.0/torque-sites-config/picksome.php on line 33 and defined in /home/deploy/RacialEquity2030/mediawiki-1.35.0/includes/Title.php:3974

I dug in a bit and was able to reproduce in dev environment (after copying the latest `TorqueConfig:ValidProposals`).

Let's smoosh the bug!

**Comment by slifty** [comment]
## Diagnosis
The lines in question can be found [here](https://github.com/OpenTechStrategies/torque-sites/blob/ccd458e005a8df06f4d13f59781e57bb6f675559/roles/picksome/files/picksome.php#L32-L36):

```
    foreach($valid_pages[1] as $valid_page) {
      if($title->equals(Title::newFromText($valid_page))) {
        return true;
      }
    }
```

I debugged a bit and found that there is a value of `$valid_page` that is causing trouble.

Specifically, `Title::newFromText()` can [return null "if the Title could not be parsed because it is invalid."](https://doc.wikimedia.org/mediawiki-core/master/php/classTitle.html#ab0be46eb5c230b76e2ff314a848401c1)

The page that is causing trouble includes a `&gt;` in it, which apparently is not a valid title.

## Solutions

1. [ ] First and most importantly we should catch instances where `newFromText` returns null and skip those entries.  We can do this either with a try / catch or by splitting the Title generation and checking for a null value.

2. We should consider whether invalid titles in the `ValidProposals` list should somehow be flagged, since that would represent a potential bug that should be caught (for instance, I don't believe this proposal could be added to PickSome as its title does not match the `ValidProposals` entry, but nobody would know that!)

**Comment by kfogel** [comment]
Wow.  First, @slifty thank you for debugging this.  Definitely one of the more wild bugs I've seen, and, not to go all Indiana Jones or anything, but I've seen some stuff.

Re your two points under Solutions:

In general, we should assume that invalid titles are going to keep causing us problems, right?  Even when it's the title of a non-proposal page, or a non-valid-proposal page, still it feels like a trap waiting to spring on us when we least expect it.  I suspect that @frankduncan has a) encountered such things before in Torque and b) has already given some thought to possible solutions.  So I guess I'm just saying confer with Frank as soon as possible, but in the meantime your order of priorities above seems right to me.

**Comment by slifty** [comment]
[Here's the information about what is restricted in a page title](https://en.wikipedia.org/wiki/Wikipedia:Page_name#Technical_restrictions_and_limitations):

```
    A pagename cannot begin with a lowercase letter in any alphabet except for the German letter ß.[5]
    A pagename cannot contain any of the following characters: # < > [ ] | { } _ (which all have special meanings in wiki syntax); the non-printable ASCII characters (coded 0–31 decimal); the delete character (coded 127 decimal); the Unicode replacement character U+FFFD �; or any HTML character codes, such as &amp;.[6] A pagename also cannot contain 3 or more continuous tildes ~~~, as these are used for marking signatures on Wikipedia.
    A pagename cannot begin with a colon :.
    A pagename cannot be . or ..; or begin with ./ or ../; or contain /./ or /../; or end with /. or /...
    A pagename cannot exceed 255 bytes in length. Be aware that non-ASCII characters may take up to four bytes in UTF-8 encoding, so the total number of characters that can fit into a title may be less than 255.
    A pagename cannot begin with any kind of namespace prefix, except a pseudo-namespace prefix by definition.
```
