### ISSUE TITLE
Not all competitions show invalid as well as valid proposals.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/torque-sites#80]
Some competitions don't show invalid as well as valid proposals.  The production competitions should always include both, as per the policy decision documented in commit a5c7e0bfeb.  See also [this Zulip conversation](https://chat.opentechstrategies.com/#narrow/stream/45-Lever-for.20Change/topic/Torque/near/95477) for more information.

(Relatedly, the name of the validity column is not standardized in the competitions that do have it, but that's issue #79.)

**Comment by frankduncan** [comment]
All the competitions have been updated to link to All Proposals
