### ISSUE TITLE
Feedback on Grants API

### ISSUE THREAD

**Issue by TomLisankie** [OpenTechStrategies/torque-sites#84]
I've had some time to use the API and write up some feedback I have on it. I realize that some of this stuff is just the result of using the `mwclient` library, I'm just providing the feedback from the perspective of a user who's looking to get the information he wants from the API as elegantly as possible.

- Early on I was trying to figure out which competitions I had been granted access to. I knew I had access to `100Change2020` but wasn't sure if I had been granted access to any of the others yet. So I went through each one and knew if I got an error that meant I didn't have access. I found myself wishing I had an endpoint where I could just ask the question "which competitions do I have access to?"

- I don't think I should have to specify the competition name when I'm looking at the returned data. Example:

  - ```python
    competition_name = "Climate2030"
    site = mwclient.Site('torque.leverforchange.org/', competition_name + '/', scheme="https")
    site.login(os.getenv("EMAIL"), os.getenv("PASSWORD"))
    proposals = site.api('torquedataconnect', format='json', path='/' + competition_name)
    print(proposals[competition_name]) # I only made a request for one competition, so why should I have to specify the `competition_name` again?```
    ```

- Here's a problem I ran into when trying to get data for `ECW2020`: I get a warning back (instead of the data itself) that says "This result was truncated because it would otherwise be larger than the limit of 8,388,608 bytes." This is strange since `100Change2017` was something like 43 MB.

- It would be nice to be able to get back a dictionary where the keys are the column names and the values are lists that contain the values for that column for each competition. The reason for this is so it's easier to put into a `pandas` DataFrame and export to a CSV for further exploration. Otherwise [the end-user has to write code to do this](https://github.com/TomLisankie/scaling-grants/blob/9211308820a6342b75fdc61b0399d9853cbdcc8c/lfc_test.py#L24) and I imagine this situation might be common with the kinds of people who might be using this API.

- I also looked at the [GuideStar API](https://help.guidestar.org/en/articles/2865344-guidestar-apis) just to have an API with somewhat related goals to compare to. Here's what I thought might be useful for this API:

  - I like the "CharityCheck PDF" idea. Say you're working with someone who wants to know specific info about a submission to a competition. Makes it easy to have a document to send to a coworker instead of getting the JSON back, formatting it yourself into an email, and sending it to them. Instead it's just a single API call.
  - "Search" is pretty cool. I can imagine it would be useful for other organizations to find out about people who have worked on areas they're looking to fund grants in.

- In addition to all of this, I found myself wishing that I could just ask for only the columns that I wanted for each competition instead of everything. For example, I don't need any information on where any of the organizations that made submissions are geographically located. It's simply not relevant and takes up space on my monitor when I'm exploring the data.

- Relevant to that I was thinking that this API would be a pretty good candidate to use GraphQL for. GraphQL has been on my mind a lot lately since I'm using it in another project (and perhaps you should take this with a grain of salt since I might be suffering from "when you're only using a hammer, everything looks like a nail" ;) ) and I think it might be useful here.

  - It might be an elegant way of handling API calls here. The user can specify exactly what data they want so you don't have to build endpoints for every assortment of data a client could want nor have to supply tons of parameters for those endpoints.

    - A problem here though is that competitions have different sets of fields. So really the solution here would be to have a GraphQL type for each competition. (Although I saw Frank mention that you guys might consider changing the column names in each of the competitions so that the same / similar columns also have the same name)

      - So say I want just the organization name and project description for all of the entries for `100Change2020`. I (the client) would construct a query like

        - ```graphql
             {
                allLFC100Change2020Entries {
                   orgName
                   projectDescription
                }
             }
          ```
            - If I was trying to do the same with REST, I might just have an endpoint like `/all-info/{competition-name}` which would give me all the information I need but also a whole bunch of stuff that I don't. Or if there were separate endpoints for each field like `/org-names/{competition}` or `/project-descriptions/{competition}`, then I'd be making multiple GET requests.

That's about it! If I think of anything else, I'll comment on this issue. Please don't hesitate to ask questions either!

**Comment by kfogel** [comment]
This is so helpful, thank you @TomLisankie!

@frankduncan, would you like us to leave all these issues in one mega-ticket, or break them out into separate tickets?  (I'd give them all an "API: " prefix on the titles, and/or an "API" label, so they're easy to find and categorize.)

**Comment by kfogel** [comment]
Also, let's break out API documentation into a separate `API.md` that we can point people to.

**Comment by frankduncan** [comment]
We've done some meetings internally, and we're going to update to have the following api that will address some of these.  I'll close the issue after it's completed, and then we can re-open for things in this list that are worth building out!

This is from my notes:
```- api
  - /competitions.json
    - just returns an array of strings
  - /competitions/<COMP>.json
    - let's have it
      - name
      - list of columns available
      - last updated?
        - this is trickier to get, because we have to start tracking it
        - ISO 8601
  - /competitions/<COMP>/proposals.json
    - list of proposal ids available
      - ordered in the order that's appropriate for the competition
  - /competitions/<COMP>/proposals/<id>.json
    - dictionary of proposal
    - Add a PUT for edit
      - pass a json objects
        - keys are fields to update
        - values are things
      - only allow PUTS in mediawiki to be passed through if the person has the torquedata-edit flag set to true
  - /competitions/<COMP>/proposals/<id>/attachments/<attachment_name>.<fmt>
  - /competitions/<COMP>/search?q=query
    - GET_ARG of "q"
    - list of proposal ids, in order of relevance
```
>     * Early on I was trying to figure out which competitions I had been granted access to. I knew I had access to `100Change2020` but wasn't sure if I had been granted access to any of the others yet. So I went through each one and knew if I got an error that meant I didn't have access. I found myself wishing I had an endpoint where I could just ask the question "which competitions do I have access to?"

In design!

>     * I don't think I should have to specify the competition name when I'm looking at the returned data. Example:
>       
>       * ```python
>         competition_name = "Climate2030"
>         site = mwclient.Site('torque.leverforchange.org/', competition_name + '/', scheme="https")
>         site.login(os.getenv("EMAIL"), os.getenv("PASSWORD"))
>         proposals = site.api('torquedataconnect', format='json', path='/' + competition_name)
>         print(proposals[competition_name]) # I only made a request for one competition, so why should I have to specify the `competition_name` again?```
>         ```

In design!

> 
>     * Here's a problem I ran into when trying to get data for `ECW2020`: I get a warning back (instead of the data itself) that says "This result was truncated because it would otherwise be larger than the limit of 8,388,608 bytes." This is strange since `100Change2017` was something like 43 MB.

This was a technical problem, that's been resolved :)  Though in the future the response should never be this big again!

> 
>     * It would be nice to be able to get back a dictionary where the keys are the column names and the values are lists that contain the values for that column for each competition. The reason for this is so it's easier to put into a `pandas` DataFrame and export to a CSV for further exploration. Otherwise [the end-user has to write code to do this](https://github.com/TomLisankie/scaling-grants/blob/9211308820a6342b75fdc61b0399d9853cbdcc8c/lfc_test.py#L24) and I imagine this situation might be common with the kinds of people who might be using this API.

I think we're moving away from this, in that getting the full dataset is no longer going to be supported.  Whoever is using the api will need to loop over all the proposals to build up the full picture in their code.

> 
>     * I also looked at the [GuideStar API](https://help.guidestar.org/en/articles/2865344-guidestar-apis) just to have an API with somewhat related goals to compare to. Here's what I thought might be useful for this API:
>       
>       * I like the "CharityCheck PDF" idea. Say you're working with someone who wants to know specific info about a submission to a competition. Makes it easy to have a document to send to a coworker instead of getting the JSON back, formatting it yourself into an email, and sending it to them. Instead it's just a single API call.

Hmmm... Interesting.  We have all the pieces via the web interface (to get a rendered pdf), but we aren't exposing those through the API.  If we come into use cases that need this, we can probably re-add.

>       * "Search" is pretty cool. I can imagine it would be useful for other organizations to find out about people who have worked on areas they're looking to fund grants in.

In design!

> 
>     * In addition to all of this, I found myself wishing that I could just ask for only the columns that I wanted for each competition instead of everything. For example, I don't need any information on where any of the organizations that made submissions are geographically located. It's simply not relevant and takes up space on my monitor when I'm exploring the data.

I think we're going to count on this to be done in the target language, rather than at the API level.  Python is a much more powerful tool than any kind of specification we could reasonably implement.

> 
>     * Relevant to that I was thinking that this API would be a pretty good candidate to use GraphQL for. GraphQL has been on my mind a lot lately since I'm using it in another project (and perhaps you should take this with a grain of salt since I might be suffering from "when you're only using a hammer, everything looks like a nail" ;) ) and I think it might be useful here.

Yeah, at this time, GraphQL is probably too much of a lift.

>       
>       * It might be an elegant way of handling API calls here. The user can specify exactly what data they want so you don't have to build endpoints for every assortment of data a client could want nor have to supply tons of parameters for those endpoints.
>         
>         * A problem here though is that competitions have different sets of fields. So really the solution here would be to have a GraphQL type for each competition. (Although I saw Frank mention that you guys might consider changing the column names in each of the competitions so that the same / similar columns also have the same name)

Yeah, this is another project!  Here's hoping.
 
> 
> That's about it! If I think of anything else, I'll comment on this issue. Please don't hesitate to ask questions either!

Thanks for the feedback!  It was super useful when taking our next steps.

**Comment by kfogel** [comment]
All above looks good to me.  Comments welcome, @TomLisankie (and anyone else)!

**Comment by TomLisankie** [comment]
Hey, just fyi, no longer on this project. Looking good though!

**Comment by frankduncan** [comment]
Closing this, as the new API has been deployed!  New api ideas should get their own issues
