### ISSUE TITLE
Separate decryption from deploy

### ISSUE THREAD

**Issue by slifty** [OpenTechStrategies/torque-sites#91]
The current deploy script checks to see if a data directory exists, and if it does not it invokes a decryption step.

After speaking with @kfogel we're going to separate that logic (and modify it a bit) from the rest of the deployment logic.  

The reasoning is that deployment may happen on a separate machine from where decryption occurs (e.g. deployment may happen via Vagrant, but figuring out a secure way to set up vagrant to [work with my gpg keys](https://superuser.com/questions/922417/gpg-agent-over-ssh-with-vagrant) is enough of a yak shave that we're opting to just have vagrant / deploy safely assume that the decryption step has already happened).

As an aside, the deploy script should probably check for the existence of the specific files it needs and get angry when they don't.

**Comment by frankduncan** [comment]
Big thumbs up!  As part of this, you'll notice that we do an md5sum for certain files.  We could probably expand that to all files as part of the sanity checking.  It may also behoove us to decrypt to one directory (decrypted data), and then have the deploy script still copy from that dir, and then unzip things.  I find I very often do things like blowing away the entire data dir for a competition before re-running the full deploy script as I'm developing the part that does the unzipping and moving of attachments around.  It would make that a smoother development process if that directory management code remained in `./deploy`

One thing to be cognizant of is disk space.  I used to run this on a 30gig AWS instance, and for some competitions, having 6 different versions of the same attachment files on one disk drive proved annoying.

**Comment by slifty** [comment]
We did not end up doing this, but rather modified the deploy scripts to accept a decryption key which can be passed in directly.
